hyperliquid:
  walletAddress: "0x36Fb7eFD55170a92327E73970D72a025c405f58F"
  privateKey: "0x0138cdf27f49bf5117f17622ace4192b4d5567d429370496d432a13429c5b254"

lighter:
  api_key: "your_lighter_api_key"
  secret: "your_lighter_secret"
  passphrase: ""  # 如果有的话

paradex:
  # 方式一：ETH 私钥 + 钱包地址
  eth_private_key: "0x2d803896c44a907f7c9b95c0cc9f698548fc91b88862dc470fbafe9cf407fc4c"
  eth_wallet_address: "0x36Fb7eFD55170a92327E73970D72a025c405f58F"

  # 方式二：Starknet 账户信息（可选，若已知）
  stark_private_key: "0x00398f8cb41f385d45e31858bb6e060e49c427a25ca3adb374606f391192cc43"
  stark_public_key: "0x02aE420D8BFe805FA29157458cdb4d51ccA9a50B01563063b36e1154bA00aB38"
  eth_address: "0x37a76b1743163C9f7D70304Cb252a73A73326fC5"

binance:
  api_key: "your_binance_api_key"
  secret: "your_binance_secret"